spring:
  datasource:
    url: jdbc:mysql://localhost:20001/flashsale?useSSL=false&serverTimezone=Asia/Seoul
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    port: 6379
    password: # 비밀번호가 설정된 경우 입력
    timeout: 2000ms
  data:
    redis:
      host: localhost
      port: 20002
      timeout: 2000ms
